app_homework/app_homework/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("quotes.urls")),
    path('user/',include('user.urls')),
    path('scrap/',include('scraping.urls'))

]

app_homework/user/urls.py
from django.urls import path, include, reverse_lazy
from . import views
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from .forms import LoginForm

app_name = 'user'

urlpatterns = [
    path('login/',
         LoginView.as_view(template_name='user/login.html', form_class=LoginForm, redirect_authenticated_user=True),
         name='login'),
    path('Registration/', views.RegisterView.as_view(), name='Registration'),
    path('logout/', LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    path('addQuote/', views.add_quote, name='addQuote'),


    path('password-reset/', PasswordResetView.as_view(template_name='user/password_reset_form.html',
                                                      email_template_name='user/password_reset_email.html',
                                                      success_url=reverse_lazy('user:password_reset_done')),
         name='password_reset'),

    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html',
                                          success_url=reverse_lazy('user:password_reset_complete')),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'),
         name='password_reset_complete'),

]

app_homework/user/models.py
from django.db import models

# Create your models here.

app_homework/user/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.forms import CharField, TextInput, EmailInput, EmailField, PasswordInput
from django import forms
from quotes.models import Author, Quote, Tag
class RegisterForm(UserCreationForm):

    username=CharField(max_length=20,min_length=3,required=True,
                       widget=TextInput(attrs={'class':'form-control'}))
    email = CharField(max_length=100,
                            required=True,
                            widget=forms.TextInput(attrs={'class':'form-control'}))
    password1 = CharField(max_length=20, min_length=4, required=True,
                         widget=PasswordInput(attrs={'class': 'form-control'}))
    password2  = CharField(max_length=20, min_length=4, required=True,
                         widget=PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model=User
        fields=['username', 'email','password1','password2']

class LoginForm(AuthenticationForm):
    username = CharField(max_length=20, min_length=3, required=True,
                         widget=TextInput(attrs={'class': 'form-control'}))
    password = CharField(max_length=20, min_length=4, required=True,
                          widget=PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model=User
        fields=['username','password']


class AddAuthor(forms.ModelForm):
    fullname=CharField(required=False,max_length=50,widget=TextInput(attrs={"class": "form-control", "id": "exampleInputEmail1"}))
    born_date=CharField(required=False,max_length=20,widget=TextInput(attrs={"class": "form-control", "id": "exampleInputEmail1"}))
    born_location=CharField(required=False,widget=TextInput(attrs={"class": "form-control", "id": "exampleInputEmail1"}))
    description=CharField(required=False,widget=TextInput(attrs={"class": "form-control", "id": "exampleInputEmail1"}))

    class Meta:
        model=Author
        fields=['fullname','born_date','born_location','description']


class AddQuote(forms.ModelForm):
    tags = CharField(widget=TextInput(attrs={"class": "form-control", "id": "exampleInputEmail1"}))
    quote=CharField(widget=TextInput(attrs={"class": "form-control", "id": "exampleInputEmail1", "style": "height: 200px;"}))


    class Meta:
        model=Quote
        fields = ['quote', 'tags']

    def clean_tags(self):
        tags = self.cleaned_data.get('tags')
        return tags.split()

app_homework/user/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseNotAllowed
from django.shortcuts import render, redirect
from django.views import View
from .forms import RegisterForm, LoginForm
from django.contrib import messages
from .forms import AddAuthor, AddQuote
from quotes.models import Tag



# Create your views here.


class RegisterView(View):
    template_name = 'user/register.html'
    form_class = RegisterForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(to='user:addQuote')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, self.template_name, context={'form': self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            messages.success(request, f'Account {username} was created')
            return redirect(to='user:login')
        return render(request, self.template_name, context={'form': self.form_class})


@login_required
def add_quote(request):
    author_form = AddAuthor()
    quotes_form = AddQuote()
    if request.method == 'POST':
        author_form = AddAuthor(request.POST)
        quotes_form = AddQuote(request.POST)
        if quotes_form.is_valid():
            quote = quotes_form.save(commit=False)
            if author_form.is_valid():
                author = author_form.save()
                quote.author = author
            author_form.save()
            quote.save()
            tag_data = request.POST.getlist('tags')
            for tag_name in tag_data:
                tag, created = Tag.objects.get_or_create(tag=tag_name)
                quote.tags.add(tag)  # Добавляем тег к цитате
            messages.success(request, 'Quote add')
            return redirect(to='user:addQuote')
    return render(request, 'user/add_quote.html', context={'quote_form': quotes_form, 'author_form': author_form})

app_homework/user/templates/user/add_quote.html
{% extends 'quotes/base.html' %}

{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<form method="post" action="">
    {% csrf_token %}
    <div class="mb-3">
        <h3>Please fill the forms</h3>
        <label for="exampleFormControlInput1" class="form-label"></label>
        {{author_form}}
    </div>
    <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label">tags</label>
        {{quote_form.tags}}
    </div>
    <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label">Quote</label>
        {{quote_form.quote}}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

app_homework/user/templates/user/login.html
{% extends 'quotes/base.html' %}

{% block content %}
<div class="container">
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li
        {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="form-group col-xs-3">
                <label for="username">Name
                    {{form.username}}
                </label>

            </div>
        </div>
        <div class="row">
            <div class="form-group col-xs-3">
                <label for="username">Password
                    {{form.password}}</label>

            </div>
        </div>
        <button type="submit" class="btn btn-primary">Login</button>
        <a href="{% url 'user:password_reset' %}" class="btn btn-primary mt-3">Забыли пароль</a>

    </form>


</div>
{% endblock %}

app_homework/user/templates/user/logout.html
{% extends 'quotes/base.html'%}

{% block content %}
<div class="container-mt-3">
    <h1>Come back please</h1>

</div>
{%endblock%}

app_homework/user/templates/user/password_reset_complete.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Password reset complete!</h2>
<a href="{% url 'user:login' %}" class="btn btn-primary mt-3">Забыли пароль</a>

{% endblock %}

app_homework/user/templates/user/password_reset_confirm.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

app_homework/user/templates/user/password_reset_done.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

app_homework/user/templates/user/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'user:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'user:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

app_homework/user/templates/user/password_reset_form.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

app_homework/user/templates/user/register.html
{% extends 'quotes/base.html' %}

{% block content %}
<div class="container">
    <h2>Register User</h2>
    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{ form.non_field_errors }}
    </div>
    {% endif %}
    <form method="post" action="{% url 'user:Registration'%}">
        {% csrf_token %}
        <input type="hidden" name="csrf_token" value="eoKPuBICAzHXfMrYnkgUNbaZcFlOTpxymdSjQtvVLhWRDEqJsGwi">
        <div class="row">
            <div class="form-group col-xs-3">
                <label for="username">Username{{form.username}}</label>
            </div>
        </div>
        <div class="row">
            <div>
                <label> Email:
                    {{ form.email }}
                </label>
                <span>{{ form.errors.email }}</span>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-xs-3">
                <label for="password1">Enter password{{form.password1}}</label>

            </div>
        </div>
        <div class="row">
            <div class="form-group col-xs-3">
                <label for="password2">Repeat password{{form.password2}}</label>

            </div>
        </div>
        <button type="submit" class="btn btn-primary" style="margin-top: 3px;">Register</button>

    </form>


</div>
{% endblock %}