app_homework/app_homework/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("quotes.urls")),
    path('user/',include('user.urls')),
    path('scrap/',include('scraping.urls'))

]

app_homework/quotes/urls.py
from django.urls import path, include
from . import views

app_name = 'quotes'

urlpatterns = [
    path('', views.main, name='root'),
    path('<int:page>', views.main, name='root_paginate'),
    path('author/<int:author_id>',views.author_data,name='author_detail'),
    path('taginfo/<tag_id>/',views.tag_data,name='tag_info')
]

app_homework/scraping/urls.py
from django.urls import path, include
from . import views

app_name = 'scraping'

urlpatterns = [
    path('to_db/',views.get_srap,name='scrap'),
]

app_homework/user/urls.py
from django.urls import path, include, reverse_lazy
from . import views
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from .forms import LoginForm

app_name = 'user'

urlpatterns = [
    path('login/',
         LoginView.as_view(template_name='user/login.html', form_class=LoginForm, redirect_authenticated_user=True),
         name='login'),
    path('Registration/', views.RegisterView.as_view(), name='Registration'),
    path('logout/', LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    path('addQuote/', views.add_quote, name='addQuote'),


    path('password-reset/', PasswordResetView.as_view(template_name='user/password_reset_form.html',
                                                      email_template_name='user/password_reset_email.html',
                                                      success_url=reverse_lazy('user:password_reset_done')),
         name='password_reset'),

    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html',
                                          success_url=reverse_lazy('user:password_reset_complete')),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'),
         name='password_reset_complete'),

]

app_homework/quotes/models.py
from django.db import models
from django.urls import reverse


# Create your models here.


class Author(models.Model):
    fullname = models.CharField()
    born_date = models.CharField()
    born_location = models.CharField()
    description = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True)


class Tag(models.Model):
    tag = models.CharField()


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

app_homework/quotes/views.py
from django.shortcuts import render
from .models import Quote,Author,Tag
from django.core.paginator import Paginator
from django.db.models import Count

# Create your views here.

def main(request,page=1):
    quote_list = Quote.objects.all().order_by('-created_at')
    author_ids = set(quote.author_id for quote in quote_list)
    authors = Author.objects.filter(id__in=author_ids)
    per_page=10
    paginator=Paginator(list(quote_list),per_page)
    quote_on_page=paginator.page(page)
    top_tags=Tag.objects.annotate(num_quotes=Count('quote')).order_by('-num_quotes')[:10]
    tag_font_sizes = {tag: 16 + tag.num_quotes // 10 for tag in top_tags}
    return render(request, 'quotes/index.html', {'quotes_list': quote_on_page, 'authors': authors,'top_tags':top_tags,'tag_font_sizes': tag_font_sizes})


def author_data(request,author_id):
    author=Author.objects.get(id=author_id)
    return render(request,'quotes/author_detail.html', {'author': author})


def tag_data(request,tag_id):
    tag = Tag.objects.get(pk=tag_id)
    quotes = Quote.objects.filter(tags=tag)
    authors = Author.objects.filter(quote__in=quotes).distinct()
    return render(request, 'quotes/quote_detail.html', context={'quotes': quotes, 'authors': authors})

app_homework/quotes/templates/quotes/author_detail.html
{% extends 'quotes/base.html' %}
{% block content %}
<div class="author-details">
    <h3 class="author-title">{{author.fullname}}</h3>
    <p><strong>Born:</strong> <span class="author-born-date">{{author.born_date}}</span> <span class="author-born-location">in Ulm, Germany</span></p>
    <p><strong>Description:</strong></p>
    <div class="author-description">
     {{author.description}}
    </div>
</div>
{% endblock %}

app_homework/quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css'%}">
    <title>Document</title>
</head>
<body>
<div class="container">
    <div class="row header-box">
        <div class="col-md-8">
            <h1>
                <a href="/" style="text-decoration: none">Quotes to Scrape</a>
            </h1>
        </div>
        <div class="col-md-4">
            {% if user.is_authenticated %}
            <div style="text-align: right;">
                <a href="{% url 'user:addQuote' %}" class="btn btn-primary mt-3">Add Quote</a>
                <form action="{% url 'user:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary mt-3">Logout</button>
                </form>
            </div>
            {% else %}
            <div style="text-align: right;">
                <a href="{% url 'user:login' %}" class="btn btn-primary mt-3">Login</a>
                <a href="{% url 'user:Registration' %}" class="btn btn-primary mt-3">Registration</a>
                <a href="{% url 'scraping:scrap' %}" class="btn btn-primary mt-3">scraping</a>
            </div>
            {% endif %}
        </div>
    </div>

    {% block content %} {% endblock %}

</div>
</body>
</html>

app_homework/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% block content %}

<div class="row">
    <div class="col-md-8">
        {% for quote in quotes_list %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">{{quote.quote}}</span>
            <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
        <a href="{% url 'quotes:author_detail' quote.author.id %}">(about)</a>
        </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                <meta class="keywords" itemprop="keywords" content="change,deep-thoughts,thinking,world">
                <a class="tag" href="{% url 'quotes:tag_info' tag.id %}">{{tag.tag}}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
        <nav>
            <ul class="pager">

                <li class="previous">
                    <a class="{%if not quotes_list.has_previous%} disabled {%endif%}"
                       href="{%if quotes_list.has_previous%} {% url 'quotes:root_paginate' quotes_list.previous_page_number %} {% else %} # {%endif%}">Previous
                        <span aria-hidden="true">→</span></a>
                </li>
                <li class="next">
                    <a class="{%if not quotes_list.has_next%} disabled {%endif%}"
                       href="{%if quotes_list.has_next%} {% url 'quotes:root_paginate' quotes_list.next_page_number %} {% else %} # {%endif%}">Next
                        <span aria-hidden="true">→</span></a>
                </li>

            </ul>
        </nav>
    </div>
    <div class="col-md-3 tags-box">

        <h2>Top Ten tags</h2>
        {% for tag in top_tags %}


        <span class="tag-item">
            <a class="tag" style="font-size: 28px" href="{% url 'quotes:tag_info' tag.id%} ">{{tag.tag}}</a>
            </span>

        {% endfor %}



    </div>

</div>
{% endblock %}

app_homework/quotes/templates/quotes/quote_detail.html
{% extends 'quotes/base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <h1><span class="text" itemprop="text">{{quote.quote}}</span></h1>
            <span>by
                {% for author in authors %}
                    {% if quote.author == author %}
                        <small class="author" itemprop="author">{{author.fullname}}</small>
                    {% endif %}
                {% endfor %}
                <a href="{% url 'quotes:author_detail' quote.author.id %}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                    <a class="tag" href="{% url 'quotes:tag_info' tag.id %}">{{tag.tag}}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
        <nav>
            <ul class="pager">
            <!-- Здесь можете добавить пагинацию, если это необходимо -->
            </ul>
        </nav>
    </div>
</div>
{% endblock %}